"""
Salesforce ID value object.

Salesforce IDs come in two forms:
  - 15-character case-sensitive IDs (returned by SOAP API, older tools)
  - 18-character case-insensitive IDs (generated by appending a 3-char checksum)

This value object:
  - Validates format (alphanumeric, correct length, correct prefix for known objects)
  - Converts 15-char IDs to 18-char canonical form
  - Provides equality based on the normalised 18-char lower-case representation
"""

from __future__ import annotations

import re
from typing import Final, Optional

from domain.exceptions.domain_exceptions import ValidationError

_SF_ID_PATTERN: Final[re.Pattern[str]] = re.compile(r"^[a-zA-Z0-9]{15}$|^[a-zA-Z0-9]{18}$")

# Salesforce object key prefixes (a small representative subset)
_OBJECT_KEY_PREFIXES: Final[dict[str, str]] = {
    "001": "Account",
    "003": "Contact",
    "006": "Opportunity",
    "00Q": "Lead",
    "500": "Case",
    "0015": "Account",  # some orgs use extended prefixes
    "0035": "Contact",
}

# Checksum alphabet for 15→18 conversion
_CHECKSUM_CHARS: Final[str] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ012345"


def _convert_15_to_18(id15: str) -> str:
    """
    Convert a 15-character Salesforce ID to its 18-character equivalent
    by appending a 3-character error-correction checksum.

    Algorithm:
        1. Split the 15-char ID into three 5-char chunks.
        2. For each chunk, reverse it.
        3. For each character in the reversed chunk, set the corresponding
           bit to 1 if the character is uppercase, else 0.
        4. Each 5-bit value indexes into _CHECKSUM_CHARS.
        5. Concatenate the three lookup characters to form the suffix.
    """
    suffix = []
    for chunk_index in range(3):
        chunk = id15[chunk_index * 5 : chunk_index * 5 + 5]
        flag = 0
        for i, ch in enumerate(reversed(chunk)):
            if ch.isupper():
                flag += 1 << i
        suffix.append(_CHECKSUM_CHARS[flag])
    return id15 + "".join(suffix)


class SalesforceId:
    """
    Immutable value object wrapping a Salesforce record ID.

    Normalises all inputs to the 18-character form for storage and comparison.
    """

    __slots__ = ("_id18", "_id15")

    def __init__(self, value: str) -> None:
        if not isinstance(value, str):
            raise ValidationError("salesforce_id", value, "Salesforce ID must be a string")

        stripped = value.strip()

        if not stripped:
            raise ValidationError("salesforce_id", value, "Salesforce ID cannot be blank")

        if not _SF_ID_PATTERN.match(stripped):
            raise ValidationError(
                "salesforce_id",
                value,
                f"Salesforce ID must be 15 or 18 alphanumeric characters (got {len(stripped)})",
            )

        if len(stripped) == 15:
            id15 = stripped
            id18 = _convert_15_to_18(stripped)
        else:
            id18 = stripped
            id15 = stripped[:15]
            # Verify checksum
            expected_18 = _convert_15_to_18(id15)
            if expected_18.upper() != id18.upper():
                raise ValidationError(
                    "salesforce_id",
                    value,
                    "18-character Salesforce ID has an invalid checksum",
                )

        object.__setattr__(self, "_id15", id15)
        object.__setattr__(self, "_id18", id18)

    # ------------------------------------------------------------------
    # Immutability
    # ------------------------------------------------------------------

    def __setattr__(self, name: str, value: object) -> None:  # type: ignore[override]
        raise AttributeError("SalesforceId is immutable")

    # ------------------------------------------------------------------
    # Value equality (case-insensitive on the 18-char form)
    # ------------------------------------------------------------------

    def __eq__(self, other: object) -> bool:
        if isinstance(other, SalesforceId):
            return self._id18.lower() == other._id18.lower()
        if isinstance(other, str):
            try:
                return self == SalesforceId(other)
            except ValidationError:
                return False
        return NotImplemented

    def __hash__(self) -> int:
        return hash(self._id18.lower())

    def __repr__(self) -> str:
        return f"SalesforceId({self._id18!r})"

    def __str__(self) -> str:
        """Return the canonical 18-character form."""
        return self._id18

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def id18(self) -> str:
        """The canonical 18-character ID (recommended for all integrations)."""
        return self._id18

    @property
    def id15(self) -> str:
        """The 15-character case-sensitive form (legacy use only)."""
        return self._id15

    @property
    def key_prefix(self) -> str:
        """The first 3 characters, which encode the Salesforce object type."""
        return self._id18[:3]

    @property
    def object_type(self) -> Optional[str]:
        """
        Return the likely Salesforce object type derived from the key prefix,
        or None if the prefix is not in the known prefix map.
        """
        return _OBJECT_KEY_PREFIXES.get(self.key_prefix)

    @property
    def is_account_id(self) -> bool:
        return self.key_prefix == "001"

    @property
    def is_contact_id(self) -> bool:
        return self.key_prefix == "003"

    @property
    def is_opportunity_id(self) -> bool:
        return self.key_prefix == "006"

    @property
    def is_lead_id(self) -> bool:
        return self.key_prefix == "00Q"

    # ------------------------------------------------------------------
    # Factory helpers
    # ------------------------------------------------------------------

    @classmethod
    def from_string(cls, value: str) -> "SalesforceId":
        """Explicit constructor alias."""
        return cls(value)

    @classmethod
    def try_parse(cls, value: str) -> "SalesforceId | None":
        """Return a SalesforceId if valid, otherwise None (never raises)."""
        try:
            return cls(value)
        except ValidationError:
            return None
